### PR TITLE
add annoucements to SiteMenu.js

### PR DESCRIPTION
**Pull request by douglasawh**
Founder Notes still needs to be added to the content dir

### CODE REVIEW

**Comment by douglasawh** [comment]
@michaelGregoire at some point, I am going to link to the YouTube page...maybe later tonight, but this looks like a decent enough block to get up on the website.

**Comment by douglasawh** [comment]
@michaelGregoire I thought of some pretty big changes for this (shouldn't take long to implement though), so if you want to look at the other one first that might make sense.

**Comment by douglasawh** [comment]
@michaelGregoire something big just came up in personal life. Can't talk about it publicly, but that means this is probably going to have to wait. However, the change in the name of the pull request gives away where I want to go with this. It isn't immediately obvious to me how to move this into a draft state.

**Comment by michaelGregoire** [comment]
Sorry that I've been slow to respond and check this out. Will try and take a look by end of week.

**Comment by douglasawh** [comment]
@michaelGregoire I finally got back to this

**Pull request merged**
